services:
  web:
    image: web
    build:
      context: ./web
      dockerfile: ./dev.Dockerfile # Comment out to use prod Dockerfile
      additional_contexts:
        - env=.
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: sync
          path: ./web
          target: /srv
    container_name: web
    env_file: .env
    ports:
      - 3000:3000

  fabdb:
    image: fabdb
    build: .
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - web
    container_name: fabdb
    depends_on:
      - psql
    env_file: .env
    environment:
      - DB_URL=psql
    ports:
      - 8080:8080

  psql:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume:
